# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ask', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_asks',
            },
        ),
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_citys',
            },
        ),
        migrations.CreateModel(
            name='Middleware',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Salary', models.IntegerField()),
                ('Lan', models.IntegerField()),
                ('City', models.IntegerField()),
                ('KeyWords', models.IntegerField()),
                ('Education', models.IntegerField()),
            ],
            options={
                'db_table': 'app_middleware',
            },
        ),
        migrations.CreateModel(
            name='ZpInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('job_category', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('working_place', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('educational', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=1024)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_zpinfo',
            },
        ),
    ]
